"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Meeting = { id: string; title: string; date: string; duration_seconds: number; participants: string[] };
const fmt = (seconds: number) => `${Math.floor(seconds / 60)}m ${seconds % 60}s`;

function MeetingModal({ close, saved }: { close: () => void; saved: () => void }) {
  const [title, setTitle] = useState(""); const [participants, setParticipants] = useState(""); const [transcript, setTranscript] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; setSaving(true);
    const lines = transcript.split("\n").map((line, i) => { const [speaker, ...rest] = line.split(":"); return { speaker: rest.length ? speaker.trim() || "Speaker" : "Speaker", text: (rest.length ? rest.join(":") : speaker).trim(), start_time_ms: i * 12000, end_time_ms: i * 12000 + 10500 }; }).filter(line => line.text);
    const response = await fetch(`${API}/api/v1/meetings`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, participants: participants.split(",").map(p => p.trim()), duration_seconds: Math.max(lines.length * 12, 60), transcript: lines, summary: lines.length ? "Meeting imported from a pasted transcript. Review the conversation and capture the follow-up work below." : "New meeting ready for notes.", action_items: [] }) });
    setSaving(false); if (response.ok) { saved(); close(); }
  };
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={submit}><div className="modal-title"><h2>Add meeting</h2><button type="button" className="icon-button" onClick={close}>×</button></div><label>Meeting title<input autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Design review" /></label><label>Participants <span className="hint">(comma separated)</span><input value={participants} onChange={e => setParticipants(e.target.value)} placeholder="Ritika, Maya" /></label><label>Paste transcript <span className="hint">(optional; use Speaker: text per line)</span><textarea value={transcript} onChange={e => setTranscript(e.target.value)} placeholder={"Ritika: Welcome everyone\nMaya: Here is the update..."} rows={7} /></label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving ? "Creating…" : "Create meeting"}</button></div></form></div>;
}

export default function Home() {
  const [meetings, setMeetings] = useState<Meeting[]>([]); const [participants, setParticipants] = useState<string[]>([]); const [search, setSearch] = useState(""); const [sort, setSort] = useState("newest"); const [person, setPerson] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [modal, setModal] = useState(false); const [toast, setToast] = useState(""); const [error, setError] = useState("");
  const load = () => { const query = new URLSearchParams({ search, sort }); if (person) query.set("participant", person); if (from) query.set("date_from", from); if (to) query.set("date_to", to); fetch(`${API}/api/v1/meetings?${query}`).then(r => r.ok ? r.json() : Promise.reject()).then(setMeetings).catch(() => setError("Could not reach the API. Start the FastAPI server on port 8000.")); };
  useEffect(() => { fetch(`${API}/api/v1/participants`).then(r => r.json()).then(setParticipants).catch(() => undefined); }, []);
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [search, sort, person, from, to]);
  const participantCount = useMemo(() => new Set(meetings.flatMap(m => m.participants)).size, [meetings]);
  const remove = async (id: string) => { if (!confirm("Delete this meeting and its transcript?")) return; await fetch(`${API}/api/v1/meetings/${id}`, { method: "DELETE" }); setToast("Meeting deleted"); load(); };
  const created = () => { setToast("Meeting created"); fetch(`${API}/api/v1/participants`).then(r => r.json()).then(setParticipants); load(); };
  return <div className="shell"><aside className="side"><div className="brand">fire<span>flies</span></div><nav className="nav"><a className="active" href="#">✦ Meetings</a><a href="#search">⌕ Search</a><a href="#">✓ Action items</a><a href="#settings">⚙ Settings <small>Coming soon</small></a></nav><div className="profile">R<div><strong>Ritika</strong><span>Personal workspace</span></div></div></aside><main className="main"><div className="top"><div><h1>My meetings</h1><p className="sub">{meetings.length} conversations · {participantCount} participants</p></div><button className="primary" onClick={() => setModal(true)}>+ Add meeting</button></div><div className="controls" id="search"><input className="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search meetings and transcripts..."/><select className="select" value={person} onChange={e => setPerson(e.target.value)}><option value="">All participants</option>{participants.map(p => <option key={p}>{p}</option>)}</select><input className="select date" aria-label="From date" type="date" value={from} onChange={e => setFrom(e.target.value)}/><input className="select date" aria-label="To date" type="date" value={to} onChange={e => setTo(e.target.value)}/><select className="select" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select></div>{error ? <div className="error">{error}</div> : <div className="card">{meetings.length ? meetings.map(m => <div className="meeting" key={m.id}><div><Link href={`/meetings/${m.id}`}>{m.title}</Link><div className="tiny">{new Date(m.date).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</div></div><div className="people">{m.participants.map(p => <span className="pill" key={p}>{p}</span>)}</div><div className="tiny">{fmt(m.duration_seconds)}</div><button aria-label={`Delete ${m.title}`} className="delete" onClick={() => remove(m.id)}>×</button></div>) : <div className="empty">No meetings match these filters.</div>}</div>}</main>{modal && <MeetingModal close={() => setModal(false)} saved={created}/>} {toast && <div className="toast" onAnimationEnd={() => setToast("")}>{toast}</div>}</div>;
}
